T = 100
N = 200
A = 100
B = 100
WORLD_DIMENSION = (A, B)
r = 1
MOVE_RANGE = ((-r, r), (-r, r))
d = 1
MESSAGE_EXCHANGE_RANGE = ((-d, d), (-d, d))
ADVERSARY_RATIO = 0.01

# Watts-Strogatz model parameters
WS_DELTA = 10
# WS_DELTA = N // 10
WS_BETA = 0.5

# User settings
MESSAGE_LIST_SIZE = 1000
MAX_VOTES_ALLOWED_ON_MESSAGE = 10000
# TODO:
MIN_TTL = 10
USER_MESSAGE_CREATION_RATE = 0.07
USER_ACT_PROBABILITY = 0.3
OWT_MIN_TRUST_VALUE = 2
USER_VOTING_ON_UNKNOWN_MESSAGES_RATE = 0.02

# Program related
UPVOTE = True
DOWNVOTE = False
