T = 100
N = 600
A = 25
B = 25
WORLD_DIMENSION = (A, B)
r = 2
MOVE_RANGE = ((-r, r), (-r, r))
d = 1
MESSAGE_EXCHANGE_RANGE = ((-d, d), (-d, d))
ADVERSARY_RATIO = 0.015

# Watts-Strogatz model parameters
WS_DELTA = 15
# WS_DELTA = N // 10
WS_BETA = 0.5

# User settings
MESSAGE_STORAGE_SIZE = 1500
MAX_VOTES_ALLOWED_ON_MESSAGE = 10000
# TODO:
MIN_TTL = 15
USER_MESSAGE_CREATION_RATE = 0.07
USER_ACT_PROBABILITY = 0.14
OWT_MIN_TRUST_VALUE = 2
USER_VOTING_ON_UNKNOWN_MESSAGES_RATE = 0.02
USER_UPVOTING_ON_MISINFORMATION_RATE = 0.3

# Program related
UPVOTE = True
DOWNVOTE = False
